steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--platform', 'linux/amd64', '-t', 'us-central1-docker.pkg.dev/k8s-assignment-niveditha/container2-repo/container2:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/k8s-assignment-niveditha/container2-repo/container2:latest']
images:
- 'us-central1-docker.pkg.dev/k8s-assignment-niveditha/container2-repo/container2:latest'
options:
  logging: CLOUD_LOGGING_ONLY